module.exports = [
	{ id: 0, name: 'Acura' },
	{ id: 1, name: 'Alfa Romeo' },
	{ id: 2, name: 'Am General' },
	{ id: 3, name: 'Aston Martin' },
	{ id: 4, name: 'Audi' },
	{ id: 5, name: 'Avanti Motors' },
	{ id: 6, name: 'Bentley' },
	{ id: 7, name: 'BMW' },
	{ id: 8, name: 'Bugatti' },
	{ id: 9, name: 'Buick' },
	{ id: 10, name: 'Cadillac' },
	{ id: 11, name: 'Chevrolet' },
	{ id: 12, name: 'Chrysler' },
	{ id: 13, name: 'Daewoo' },
	{ id: 14, name: 'Daimler' },
	{ id: 15, name: 'Dodge' },
	{ id: 16, name: 'Ferrari' },
	{ id: 17, name: 'FIAT' },
	{ id: 18, name: 'Fisker' },
	{ id: 19, name: 'Ford' },
	{ id: 20, name: 'Genesis' },
	{ id: 21, name: 'GMC' },
	{ id: 22, name: 'Honda' },
	{ id: 23, name: 'Hummer' },
	{ id: 24, name: 'Hyundai' },
	{ id: 25, name: 'Infiniti' },
	{ id: 26, name: 'Isuzu' },
	{ id: 27, name: 'Jaguar' },
	{ id: 28, name: 'Jeep' },
	{ id: 29, name: 'Kia' },
	{ id: 30, name: 'Koenigsegg' },
	{ id: 31, name: 'Lamborghini' },
	{ id: 32, name: 'Land Rover' },
	{ id: 33, name: 'Lexus' },
	{ id: 34, name: 'Lincoln' },
	{ id: 35, name: 'Lotus' },
	{ id: 36, name: 'Maserati' },
	{ id: 37, name: 'Maybach' },
	{ id: 38, name: 'Mazda' },
	{ id: 39, name: 'McLaren' },
	{ id: 40, name: 'Mercedes-Benz' },
	{ id: 41, name: 'Mercury' },
	{ id: 42, name: 'Mini' },
	{ id: 43, name: 'Mitsubishi' },
	{ id: 44, name: 'Morgan' },
	{ id: 45, name: 'Nissan' },
	{ id: 46, name: 'Oldsmobile' },
	{ id: 48, name: 'Plymouth' },
	{ id: 49, name: 'Pontiac' },
	{ id: 50, name: 'Porsche' },
	{ id: 51, name: 'Qvale' },
	{ id: 52, name: 'RAM' },
	{ id: 53, name: 'Rolls-Royce' },
	{ id: 54, name: 'Saab' },
	{ id: 55, name: 'Saleen' },
	{ id: 56, name: 'Saturn' },
	{ id: 57, name: 'Scion' },
	{ id: 57, name: 'Smart' },
	{ id: 57, name: 'Spyker' },
	{ id: 57, name: 'Subaru' },
	{ id: 57, name: 'Suzuki' },
	{ id: 57, name: 'Tesla' },
	{ id: 57, name: 'Toyota' },
	{ id: 57, name: 'Volkswagen' },
	{ id: 57, name: 'Volvo' },
];
